FROM node:20-alpine
RUN apk add --no-cache ffmpeg
WORKDIR /app
ENV PNPM_HOME=/pnpm
RUN corepack enable
COPY . /app
RUN pnpm install --filter backend --prod --ignore-scripts --no-frozen-lockfile
EXPOSE 3000
CMD ["pnpm","--filter","backend","run","start"]

